package main

import . "github.com/vuho-pg/esq/codegen/builder"

func fullTextQueryBuild() error {
	return Run(
		Map("Match", Struct("Match",
			Field("Query").Any().Required(),
			Field("Analyzer").String(),
			Field("AutoGenerateSynonymsPhraseQuery").Bool(),
			Field("Fuzziness").String(),
			Field("PrefixLength").Int(),
			Field("MaxExpansions").Int(),
			Field("FuzzyTranspositions").Bool(),
			Field("FuzzyRewrite").String(),
			Field("Lenient").Bool(),
			Field("Operator").Enum(),
			Field("MinimumShouldMatch").String(),
			Field("ZeroTermsQuery").Enum(),
		)).Implement(queryInterface),
		Map("MatchBoolPrefix", Struct("MatchBoolPrefix",
			Field("Query").Any().Required(),
			Field("Analyzer").String(),
			Field("Fuzziness").String(),
			Field("MinimumShouldMatch").String(),
			Field("PrefixLength").Int(),
			Field("MaxExpansions").Int(),
			Field("FuzzyTranspositions").Bool(),
			Field("FuzzyRewrite").String(),
		)).Implement(queryInterface),
		Map("MatchPhrase", Struct("MatchPhrase",
			Field("Query").Any().Required(),
			Field("Analyzer").String(),
			Field("ZeroTermsQuery").Enum(),
		)).Implement(queryInterface),
		Map("MatchPhrasePrefix", Struct("MatchPhrasePrefix",
			Field("Query").String().Required(),
			Field("Analyzer").String(),
			Field("MaxExpansions").Int(),
			Field("Slop").Int(),
			Field("ZeroTermsQuery").Enum(),
		)).Implement(queryInterface),
		Map("CombinedFields", Struct("CombinedFields",
			Field("Fields").String().Required().Array(),
			Field("Query").String().Required(),
			Field("AutoGenerateSynonymsPhraseQuery").Bool(),
			Field("Operator").Enum(),
			Field("MinimumShouldMatch").String(),
			Field("ZeroTermsQuery").Enum(),
		)).Implement(queryInterface),
		Map("MultiMatch", Struct("MultiMatch",
			Field("Query").String().Required(),
			Field("Fields").String().Required().Array(),
			Field("Type").String(),
			Field("Analyzer").String(),
			Field("Boost").Float64(),
			Field("Operator").Enum(),
			Field("MinimumShouldMatch").String(),
			Field("Fuzziness").String(),
			Field("Lenient").Bool(),
			Field("PrefixLength").Int(),
			Field("MaxExpansions").Int(),
			Field("FuzzyRewrite").String(),
			Field("ZeroTermsQuery").Enum(),
			Field("CutOffFrequency").Float64(),
			Field("AutoGenerateSynonymsPhraseQuery").Bool(),
			Field("FuzzyTranspositions").Bool(),
		)).Implement(queryInterface),
		Map("QueryString", Struct("QueryString",
			Field("Query").String().Required(),
			Field("DefaultField").String(),
			Field("AllowLeadingWildcard").Bool(),
			Field("AnalyzeWildcard").Bool(),
			Field("Analyzer").String(),
			Field("AutoGenerateSynonymsPhraseQuery").Bool(),
			Field("Boost").Float64(),
			Field("DefaultOperator").Type("Operator"),
			Field("EnablePositionIncrements").Bool(),
			Field("Fields").String().Array(),
			Field("Fuzziness").String(),
			Field("FuzzyMaxExpansions").Int(),
			Field("FuzzyPrefixLength").Int(),
			Field("FuzzyTranspositions").Bool(),
			Field("Lenient").Bool(),
			Field("MaxDeterminizedStates").Int(),
			Field("MinimumShouldMatch").String(),
			Field("QuoteAnalyzer").String(),
			Field("PhraseSlop").Int(),
			Field("QuoteFieldSuffix").String(),
			Field("Rewrite").String(),
			Field("TimeZone").String(),
		)).Implement(queryInterface),
		Map("SimpleQueryString", Struct("SimpleQueryString",
			Field("Query").String().Required(),
			Field("Fields").String().Array(),
			Field("DefaultOperator").Type("Operator"),
			Field("AnalyzeWildcard").Bool(),
			Field("Analyzer").String(),
			Field("AutoGenerateSynonymsPhraseQuery").Bool(),
			Field("Flags").String(),
			Field("FuzzyMaxExpansions").Int(),
			Field("FuzzyPrefixLength").Int(),
			Field("FuzzyTranspositions").Bool(),
			Field("Lenient").Bool(),
			Field("MinimumShouldMatch").String(),
			Field("QuoteFieldSuffix").String(),
		)).Implement(queryInterface),
	)
}
